import {
  Armchair,
  Baby,
  BedDouble,
  Cigarette,
  Cookie,
  Croissant,
  CupSoda,
  Dog,
  Flame,
  Gamepad2,
  GlassWater,
  HeartPulse,
  House,
  Package,
  Palette,
  PartyPopper,
  PencilRuler,
  PlugZap,
  Shirt,
  Snowflake,
  Sofa,
  Store,
  Soup,
  SprayCan,
  Wheat,
  Wine,
  Wrench,
  Tag,
} from "lucide-react";

const CATEGORY_ICON_BY_KEY = {
  "frozen-food": Snowflake,
  "grill-chill": Flame,
  smokes: Cigarette,
  "games-toys": Gamepad2,
  fashion: Shirt,
  "ibilemart-trading-operations": Store,
  "seasonal-events": PartyPopper,
  "electronic-electrical": PlugZap,
  "wine-spirits": Wine,
  drinks: CupSoda,
  "water-beverages": GlassWater,
  stationeries: PencilRuler,
  "personal-care": HeartPulse,
  "pantry-dry-ingredient": Wheat,
  "home-kitchen": House,
  "health-beauty": HeartPulse,
  "formula-feeding": Baby,
  "cosmetics-beauty": Palette,
  "cleaning-laundry": SprayCan,
  "canine-care-food": Dog,
  "breakfast-cereals": Soup,
  "biscuits-confectioneries": Cookie,
  bakery: Croissant,
  "baby-wipes-diaper": Baby,
  "baby-health-care": HeartPulse,
  box: Package,
  drink: CupSoda,
  food: Soup,
  bed: BedDouble,
  lounge: Sofa,
  furniture: Armchair,
  tools: Wrench,
  clothing: Shirt,
  gift: PartyPopper,
  tag: Tag,
};

const CATEGORY_NAME_MATCHES = [
  ["frozen", "frozen-food"],
  ["grill", "grill-chill"],
  ["smoke", "smokes"],
  ["game", "games-toys"],
  ["toy", "games-toys"],
  ["fashion", "fashion"],
  ["ibilemart trading", "ibilemart-trading-operations"],
  ["trading operation", "ibilemart-trading-operations"],
  ["seasonal", "seasonal-events"],
  ["event", "seasonal-events"],
  ["electronic", "electronic-electrical"],
  ["electrical", "electronic-electrical"],
  ["wine", "wine-spirits"],
  ["spirit", "wine-spirits"],
  ["water", "water-beverages"],
  ["beverage", "water-beverages"],
  ["drink", "drinks"],
  ["stationer", "stationeries"],
  ["personal", "personal-care"],
  ["pantry", "pantry-dry-ingredient"],
  ["dry ingredient", "pantry-dry-ingredient"],
  ["home", "home-kitchen"],
  ["kitchen", "home-kitchen"],
  ["health", "health-beauty"],
  ["formula", "formula-feeding"],
  ["feeding", "formula-feeding"],
  ["cosmetic", "cosmetics-beauty"],
  ["beauty", "cosmetics-beauty"],
  ["clean", "cleaning-laundry"],
  ["laundry", "cleaning-laundry"],
  ["canine", "canine-care-food"],
  ["dog", "canine-care-food"],
  ["breakfast", "breakfast-cereals"],
  ["cereal", "breakfast-cereals"],
  ["biscuit", "biscuits-confectioneries"],
  ["confection", "biscuits-confectioneries"],
  ["bakery", "bakery"],
  ["diaper", "baby-wipes-diaper"],
  ["baby wipe", "baby-wipes-diaper"],
  ["baby", "baby-health-care"],
];

export function getCategoryIcon(iconKey, categoryName) {
  const normalizedKey = String(iconKey || "").trim().toLowerCase();
  if (CATEGORY_ICON_BY_KEY[normalizedKey]) return CATEGORY_ICON_BY_KEY[normalizedKey];

  const normalizedName = String(categoryName || "").trim().toLowerCase();
  const match = CATEGORY_NAME_MATCHES.find(([term]) => normalizedName.includes(term));
  return match ? CATEGORY_ICON_BY_KEY[match[1]] : Package;
}
